# @server_url = https://dhoolia.ngrok.io
@server_url = http://ec2-54-90-218-231.compute-1.amazonaws.com

### Onboard: New Project
PUT {{server_url}}/onboard HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "repo_full_name": "pdhoolia/se-agent",
    "src_folder": "se_agent",
    "main_branch": "main"
}

### Onboard / Refresh: Existing Project
PUT {{server_url}}/onboard HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "repo_full_name": "pdhoolia/se-agent-test-repo",
    "src_folder": "se_agent_test_repo",
    "main_branch": "main"
}